### ISSUE TITLE
New Parameter disables to read from SepaTransfer

### ISSUE THREAD

**Issue by eporsche** [Mestrona/aqbanking-php#10]
Hi,

this new line:

https://github.com/Mestrona/aqbanking-php/blob/576442bcfffab8dbe654ded2ff6b72238dec0cf9/src/AqBanking/Command/RenderContextFileToXMLCommand.php#L20

Actually disables to read the result set from a SepaTransferCommand.  For both the sepa transfer and  fetch balance statements the same RenderContextFileToXMLCommand is used to get the xml. I would like to remove this parameter and make SepaTransferCommand working again.

**Comment by amenk** [comment]
Interesting, but I inserted it for a reason, can we make it work for both cases?

**Comment by eporsche** [comment]
#11
