### ISSUE TITLE
Builds are failing

### ISSUE THREAD

**Issue by amenk** [Mestrona/aqbanking-php#22]
https://github.com/Mestrona/aqbanking-php/actions/runs/7100180749/job/19325710701

@grummbeer mind having a look :-) ?

**Comment by grummbeer** [comment]
yes :-) on the way.

**Comment by grummbeer** [comment]
> Der eine Test schlägt fehl, nicht weil das Ergebnis nicht stimmt, sondern weil der Test selbst (mockery) irgendwas hat.

What i interpreted as a fault of mockery was i fact the failing test :-) The Argument `--transactiontype=statement` was missing.
