### ISSUE TITLE
Should SetAppropriateITanModeCommand removed?

### ISSUE THREAD

**Issue by grummbeer** [Mestrona/aqbanking-php#28]
Should the command [`SetAppropriateITanModeCommand`](https://github.com/Mestrona/aqbanking-php/blob/master/src/Command/SetAppropriateITanModeCommand.php) be removed or deprecated?

As far i can see, this "command" makes no sense. I'am not sure if this is doing what expected.  

- does not work, wrong command 
- handle with HBCIVersion but set a itanmode?
- is not a aqbanking command. It is a collection of commands, more like a function of a (userland/api) controller.
- if an available ITanMode is set, is it the one the user wants/is ready to use?

for example
```
- 6910 (F910/V6/P2): HHD1.3.0 (chipTAN manuell) [available]
              ^
              This is recognized as "HBCIVersion"? Is it the HBCI-Version?
```

My HBCI Version is '300', so …

**Comment by amenk** [comment]
Looks like this is a very old command, I was not even aware that it exists.

[mbank uses ](https://github.com/Mestrona/mbank/blob/2f175ffb3ebfa0884596f874bb58478b0e213d2f/app/Account.php#L106)the newer command, [setITanMode](https://github.com/Mestrona/aqbanking-php/blob/master/src/Command/SetITanModeCommand.php) for the configured mode.

I think it can be removed.
